//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int IdCalls { get; set; }
        public Nullable<System.DateTime> DateCall { get; set; }
        public Nullable<int> LongCall { get; set; }
        public int idUser { get; set; }
        public int idLead { get; set; }
    
        public virtual Lead Lead { get; set; }
        public virtual User User { get; set; }

        
    }
}
